#!/usr/bin/python

#
#  First draft for a monitor script
#  It checks for "FAILED" string in 
#  condor output files
#
    
import commands
import os
import sys
import threading

#  !!!! NEED A CHECK THAN LEN(ARGV)==3  !!!!!
DATE=sys.argv[1]
STRING=sys.argv[2]
STRING=STRING.replace(' ','\ ')
STRING=STRING.replace(':','\:')


class CMD(threading.Thread):
        def __init__(self, dir):
                threading.Thread.__init__(self)
                self.dir = dir

        def run(self):
                self.out = commands.getoutput('grep %s %s/*out' %(STRING, self.dir))


threads = {}
outputs = {}

DIRS = os.listdir(DATE)
for APFQUEUE in DIRS:
        t = CMD('%s/%s' %(DATE, APFQUEUE))
        threads[APFQUEUE] = t
        t.start()

for APFQUEUE in DIRS:
        threads[APFQUEUE].join()

        outputs[APFQUEUE] = threads[APFQUEUE].out
        if outputs[APFQUEUE]:
                print('directory : %s'%APFQUEUE)
                for line in outputs[APFQUEUE].split('\n'):
                        print('  %s' %line)
                print('')

