#!/bin/bash
#
#	/etc/rc.d/init.d/factory
#
# Starts the autopyfactory daemon
#
# chkconfig: 345 26 74
# description: Submit pilot jobs to grid sites. 
# processname: factory
# config: /etc/apf/factory.conf 
# pidfile: /var/run/factory.pid
#
#

### BEGIN INIT INFO
# Provides: factory.py
# Required-Start: $syslog $local_fs
# Required-Stop: $syslog $local_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop autopyfactory
# Description: Submit PANDA pilots. 
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Determine usage context (root means RPM, non-root means home directory) and set
# paths accordingly.  

if [ `id -u` = 0 ]; then
  SYSCONF=/etc/sysconfig/factory.sysconfig
  BINDIR=/usr/bin
  ETCDIR=/etc/apf
  PIDFILE=/var/run/factory.pid
else
  SYSCONF=$HOME/etc/factory.sysconfig
  BINDIR=$HOME/bin
  ETCDIR=$HOME/etc
  PIDFILE=$HOME/var/run/factory.pid
fi

CONFFILE=$ETCDIR/factory.conf

# Source settings from sysconfig
# overriding default if present
if [ -f $SYSCONF ]; then
   . $SYSCONF
fi

if [ -n "$GRIDSETUP" ]; then
   . $GRIDSETUP
fi



RETVAL=0
#
# See how we were called.
#
check() {
	
	# Check if factory.py is executable
	test -x $BINDIR/factory || exit 5
}

start() {
	# Check if it is already running
	if [ ! -f $PIDFILE ]; then
		echo -n $"Starting APF daemon: "	
	    daemon --pidfile=$PIDFILE "$BINDIR/factory --conf $CONFFILE $OPTIONS &"
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch $PIDFILE
	    echo
	else
	    echo "$0: PID file exists: $PIDFILE" 
	fi
	return $RETVAL
}

stop() {

	check
	echo -n $"Stopping factory daemon: "
	killproc -p $PIDFILE factory
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $PIDFILE
	echo
    return $RETVAL
}


restart() {
	stop
	start
}	

reload() {

	check
	
	trap "" SIGHUP
	action $"Reloading factory daemon:" killall -HUP factory.py
	RETVAL=$?
	return $RETVAL
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	echo "$0: Unimplemented feature."
    RETVAL=3
	;;
force-reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/factory ]; then
	    restart
	fi
	;;
status)
	status factory
	RETVAL=$?
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload}"
	RETVAL=2
esac

exit $RETVAL
