.\" Process this file with
 autopyfactory-proxy.conf.5
.\"
.TH AUTOPYFACTORY MONITOR.CONF 5 "JUNE 2013" Linux "User Manuals"
.SH NAME
AutoPyFactory monitor.conf \- monitor.conf configuration file for autopyfactory
.SH DESCRIPTION
.B monitor.conf

/etc/apf/monitor.conf  Configuration file for the monitor setup for AutoPyFactory.

.B monitorplugin 

the type of plugin to handle this monitor instance 

.B monitorURL   

URL for the web monitor 


